### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by Kiwamm** [Herixth/SCU-reward-platform#17]
你好，我想问下如果部署到django项目到服务器上，服务器上要求有mysql吗。我看你要求环境里好像没说mysql的环境，所以所有疑惑。

**Comment by hx-w** [comment]
谢谢你的关注，这个项目里的数据库使用的是sqlite，不需要额外装mysql。
此外，本项目已经停止维护，这是我们的第一次django练习，代码结构混乱，文档已经过时，并不建议直接将此项目部署到服务器。
如果您有django或者网站开发相关的问题欢迎讨论，这是我的邮箱: 17361019875@163.com

**Comment by Kiwamm** [comment]
好的，谢谢了，我想跟着这个项目学习下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hx-w/SCU-reward-platform"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月6日(星期天) 中午12:54
收件人:&nbsp;"hx-w/SCU-reward-platform"<SCU-reward-platform@noreply.github.com&gt;;
抄送:&nbsp;"1449424006"<1449424006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hx-w/SCU-reward-platform] 数据库问题 (#17)





 
谢谢你的关注，这个项目里的数据库使用的是sqlite，不需要额外装mysql。
 此外，本项目已经停止维护，这是我们的第一次django练习，代码结构混乱，文档已经过时，并不建议直接将此项目部署到服务器。
 如果您有django或者网站开发相关的问题欢迎讨论，这是我的邮箱: 17361019875@163.com

**Comment by Kiwamm** [comment]
我以前都是用的Java的springboot，还没咋用过django
